export type Realization = {
  id: string;
  category: string;
  categorySlug: string;
  investor: string;
  scope: string;
  image: string;
};

export const realizationCategories = [
  { slug: "obiekty-przemyslowe", name: "Obiekty przemysłowe" },
  { slug: "obiekty-handlowe", name: "Obiekty handlowe" },
  { slug: "obiekty-uzytecznosci-publicznej", name: "Obiekty użyteczności publicznej" },
  { slug: "szpitale-i-placowki-medyczne", name: "Szpitale i placówki medyczne" },
  { slug: "banki", name: "Banki" },
  { slug: "obiekty-biurowe-i-hotele", name: "Obiekty biurowe i hotele" },
  { slug: "pozostale-obiekty", name: "Pozostałe obiekty" },
];

export const realizations: Realization[] = [
  {
    id: "obiekty-przemyslowe-1",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Hillwood Zgierz",
    scope: "Szeroki zakres montażowy - klimatyzacja, wentylacja, C.T., C.O., hydraulika",
    image: new URL("../assets/realizations/obiekty-przemyslowe-01-hillwood-zgierz.webp", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-2",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Dino Polska S. A. Lubień Kujawski",
    scope: "Szeroki zakres montażowy - CO, CT, kotłownia, klimatyzacja, wentylacja z centralami wentylacyjnymi, hudraulika.",
    image: new URL("../assets/realizations/obiekty-przemyslowe-02-dino-polska-s-a-lubien-kujawski.webp", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-3",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Italmetal Jelcz Laskowice",
    scope: "Szeroki zakres montażowy - promienniki, destryfikatory, CO, CT, kotłownia, wentylatory. Montaż systemów - klimatyzacja VRF Fujitsu, wentylacja wraz z centralą wentylacyjną.",
    image: new URL("../assets/realizations/obiekty-przemyslowe-03-italmetal-jelcz-laskowice.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-4",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "ARPSTAL Poznań",
    scope: "Montaż systemu wentylacji oraz klimatyzacji typu Multi Fujitsu",
    image: new URL("../assets/realizations/obiekty-przemyslowe-04-arpstal-poznan.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-5",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "P11 Group",
    scope: "Montaż systemu wentylacji oraz klimatyzacji typu jeden do jeden",
    image: new URL("../assets/realizations/obiekty-przemyslowe-05-p11-group.png", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-6",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Teamtechnik Production Technology Sp. z o.o.",
    scope: "Montaż systemu wody lodowej, klimakonwektorów.",
    image: new URL("../assets/realizations/obiekty-przemyslowe-06-teamtechnik-production-technology-sp-z-o-o.jpeg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-7",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Zakłady Drobiarskie Farmio Sp. z o.o.",
    scope: "Montaż klimakonwektorów, klimatyzatorów typu Split, central wentylacyjnych.",
    image: new URL("../assets/realizations/obiekty-przemyslowe-07-zak-ady-drobiarskie-farmio-sp-z-o-o.png", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-8",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Eko Okna S.A.",
    scope: "Montaż systemów VRF, Split, systemu pracy naprzemiennej, wentylacji, central wentylacyjnych.",
    image: new URL("../assets/realizations/obiekty-przemyslowe-08-eko-okna-s-a.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-9",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "KGHM Polska Miedź S.A.",
    scope: "Montaż systemów VRF, Split, Multi Split, wentylacji mechanicznej, agregatów skraplajacych central wentylacyjnych, szaf klimatyzacji precyzyjnej.\nŁączna moc zainstalowanych urządzeń przez ostatnie lata 2mW.",
    image: new URL("../assets/realizations/obiekty-przemyslowe-09-kghm-polska-miedz-s-a.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-10",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "PGE Górnictwo i Energetyka Konwencjonalna S.A. Oddział Elektrownia Turów",
    scope: "Montaż systemów klimatyzacji w pomieszczeniach technicznych",
    image: new URL("../assets/realizations/obiekty-przemyslowe-10-pge-gornictwo-i-energetyka-konwencjonalna-s-a-oddzia-elektro.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-11",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Świeże i Zielone spółka z o.o. spółka komandytowa",
    scope: "Montaż systemów wody lodowej, wentylacji mechanicznej",
    image: new URL("../assets/realizations/obiekty-przemyslowe-11-swieze-i-zielone-spo-ka-z-o-o-spo-ka-komandytowa.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-12",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Dongseo Display Poland",
    scope: "Montaż systemów klimatyzacji Multi V LG oraz systemu Wentylacji",
    image: new URL("../assets/realizations/obiekty-przemyslowe-12-dongseo-display-poland.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-13",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "LUMAG Sp. z o.o.",
    scope: "Montaż systemów VRF , Split, Multi Split, agregatów chłodniczych, laczna moc urzadzen 1mW",
    image: new URL("../assets/realizations/obiekty-przemyslowe-13-lumag-sp-z-o-o.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-14",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Ericpol",
    scope: "Montaż systemów Citi Multi Mitsubishi z odzyskiem ciepła 1mW.",
    image: new URL("../assets/realizations/obiekty-przemyslowe-14-ericpol.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-15",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Enea Poznań",
    scope: "Dostawa oraz montaż systemu VRF",
    image: new URL("../assets/realizations/obiekty-przemyslowe-15-enea-poznan.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-16",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Green Horizon Łódź",
    scope: "Montaż systemów VRF",
    image: new URL("../assets/realizations/obiekty-przemyslowe-16-green-horizon-odz.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-17",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Kwadraciak Poznań",
    scope: "Montaż systemów VRF",
    image: new URL("../assets/realizations/obiekty-przemyslowe-17-kwadraciak-poznan.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-18",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Okraglak Poznań",
    scope: "Montaż Systemów VRF oraz Uruchomienie wraz z konfiguracją Systemów Wody Lodowej",
    image: new URL("../assets/realizations/obiekty-przemyslowe-18-okraglak-poznan.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-19",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Protea Sp. z o.o. Oddział Kluczbork",
    scope: "Montaż urządzeń typu Split na obiektach w całej Polsce, tylko klimatyzatory Fujitsu , Sharp",
    image: new URL("../assets/realizations/obiekty-przemyslowe-19-protea-sp-z-o-o-oddzia-kluczbork.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-20",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Solar Company S.A.",
    scope: "Klimatyzatory Typu Multi Split, Split , agregaty skraplające chłodnic central wentylacyjnych wraz z pełną automatyką Mitsubishi",
    image: new URL("../assets/realizations/obiekty-przemyslowe-20-solar-company-s-a.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-21",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Pudliszki HJH Polska S.A.",
    scope: "Klimatyzatory Typu Multi Split naścienny Fujitsu",
    image: new URL("../assets/realizations/obiekty-przemyslowe-21-pudliszki-hjh-polska-s-a.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-22",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Pałac Książęcy w Żaganiu Sp. z o.o. - Basen Żagań",
    scope: "Klimatyzatory typu Multi Split Fujitsu, agregaty skraplające chłodnic central wentylacyjnych wraz z pełną automatyką Mitsubishi",
    image: new URL("../assets/realizations/obiekty-przemyslowe-22-pa-ac-ksiazecy-w-zaganiu-sp-z-o-o-basen-zagan.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-23",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "P.T.H.U. HYDRO-MARKO Maria Pluta",
    scope: "System wentylacji Mechanicznej – Hala Produkcyjna",
    image: new URL("../assets/realizations/obiekty-przemyslowe-23-p-t-h-u-hydro-marko-maria-pluta.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-24",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Algeco - kontenery",
    scope: "Montaż urządzeń typu Split na obiektach w całej Polsce, tylko klimatyzatory Fujitsu , Sharp",
    image: new URL("../assets/realizations/obiekty-przemyslowe-24-algeco-kontenery.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-25",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Kimball Poznań Sp. z o.o.",
    scope: "Montaż klimatyzatorów typu Split naścienny Fujitsu",
    image: new URL("../assets/realizations/obiekty-przemyslowe-25-kimball-poznan-sp-z-o-o.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-przemyslowe-26",
    category: "Obiekty przemysłowe",
    categorySlug: "obiekty-przemyslowe",
    investor: "Imperial Tobacco Polska S.A.",
    scope: "Instalacja szaf klimatyzacji precyzyjnej, klimatyzatory Split naścienny",
    image: new URL("../assets/realizations/obiekty-przemyslowe-26-imperial-tobacco-polska-s-a.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-1",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Mercator Sp. z o. o. Poznań",
    scope: "Montaż systemów klimatyzacji VRF marki LG",
    image: new URL("../assets/realizations/obiekty-handlowe-01-mercator-sp-z-o-o-poznan.jpeg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-2",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "PH Lubin",
    scope: "Montaż systemów klimatyzacji VRF marki Fujitsu, wentylacji, montaż systemów CO oraz elementów kotłowni",
    image: new URL("../assets/realizations/obiekty-handlowe-02-ph-lubin.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-3",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Giant Office",
    scope: "Montaż systemów klimatyzacji VRF marki LG",
    image: new URL("../assets/realizations/obiekty-handlowe-03-giant-office.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-4",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "M - Park Słupca",
    scope: "Montaż systemu klimatyzacji Fujitsu",
    image: new URL("../assets/realizations/obiekty-handlowe-04-m-park-s-upca.png", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-5",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Galeria Handlowa Citi Center Poznań",
    scope: "Montaż systemów wentylacji mechanicznej pomieszczen technicznych",
    image: new URL("../assets/realizations/obiekty-handlowe-05-galeria-handlowa-citi-center-poznan.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-6",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "MERCUS SA",
    scope: "Montaż systemów klimatyzacji",
    image: new URL("../assets/realizations/obiekty-handlowe-06-mercus-sa.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-7",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Grupa Lotos SA",
    scope: "Montaż systemów klimatyzacji, wentylacji",
    image: new URL("../assets/realizations/obiekty-handlowe-07-grupa-lotos-sa.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-8",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "PKN ORLEN SA",
    scope: "Montaż systemów klimatyzacji, wentylacji",
    image: new URL("../assets/realizations/obiekty-handlowe-08-pkn-orlen-sa.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-9",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Wydawnictwo Kropka",
    scope: "Montaż systemów klimatyzacji VRF Fujitsu oraz wentylacji mechanicznej",
    image: new URL("../assets/realizations/obiekty-handlowe-09-wydawnictwo-kropka.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-10",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Citi Center Poznań",
    scope: "Dostawa oraz montaż elementów wentylacji mechanicznej pomieszczeń technicznych obiektu",
    image: new URL("../assets/realizations/obiekty-handlowe-10-citi-center-poznan.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-11",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Lokale 4F",
    scope: "Montaż Systemów Wentylacji Mechanicznej oraz Klimatyzacji",
    image: new URL("../assets/realizations/obiekty-handlowe-11-lokale-4f.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-12",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Lokale Szachownica",
    scope: "Montaż Systemów Wentylacji oraz Klimatyzacji",
    image: new URL("../assets/realizations/obiekty-handlowe-12-lokale-szachownica.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-13",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Zabytkowa Kamienica z adaptacją na pomieszczenia biurowe.",
    scope: "Montaż klimatyzatorów opartych na systemach Multi oraz wentylacji mechanicznej opartej na centralach wentylacyjnych.",
    image: new URL("../assets/realizations/obiekty-handlowe-13-zabytkowa-kamienica-z-adaptacja-na-pomieszczenia-biurowe.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-14",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Power Bike Sp. z o.o.",
    scope: "Klimatyzatory system VRV Daikin typ Split kanałowy",
    image: new URL("../assets/realizations/obiekty-handlowe-14-power-bike-sp-z-o-o.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-15",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Przedsiębiorstwo Budowlano-Handlowe Stanisław Hadrzyński",
    scope: "Klimatyzatory Typu Split naścienny Fujitsu",
    image: new URL("../assets/realizations/obiekty-handlowe-15-przedsiebiorstwo-budowlano-handlowe-stanis-aw-hadrzynski.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-16",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Unirol Borek WLKP.",
    scope: "Montaż klimatyzatorów typu Split",
    image: new URL("../assets/realizations/obiekty-handlowe-16-unirol-borek-wlkp.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-17",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "JUAN SP.J. Oddział Bydgoszcz / Białe Błota",
    scope: "Montaż Klimatyzatorów Kanałowych , Split naścienny",
    image: new URL("../assets/realizations/obiekty-handlowe-17-juan-sp-j-oddzia-bydgoszcz-bia-e-b-ota.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-18",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "JUAN SP.J. Oddział Wrocław / Długołęka",
    scope: "Montaż klimatyzatorów kanałowych, kasetonowych - Fujitsu",
    image: new URL("../assets/realizations/obiekty-handlowe-18-juan-sp-j-oddzia-wroc-aw-d-ugo-eka.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-19",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Galeria Kaskada Szczecin",
    scope: "Montaż klimatyzatorów Typu VRF , Multi Split , Split Mitsubishi",
    image: new URL("../assets/realizations/obiekty-handlowe-19-galeria-kaskada-szczecin.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-handlowe-20",
    category: "Obiekty handlowe",
    categorySlug: "obiekty-handlowe",
    investor: "Galeria Victoria Wałbrzych",
    scope: "Montaż klimatyzatorów typu Split , Multi Split - Fujitsu",
    image: new URL("../assets/realizations/obiekty-handlowe-20-galeria-victoria-wa-brzych.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-1",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Izba Administracji Skarbowej w Poznaniu",
    scope: "Montaż systemów klimatyzacji Multi marki Fujitsu.",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-01-izba-administracji-skarbowej-w-poznaniu.webp", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-2",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "ZUS Ostrów Wlkp.",
    scope: "Montaż systemów klimatyzacji marki Innova.",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-02-zus-ostrow-wlkp.webp", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-3",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "PSSE Piła",
    scope: "Montaż systemu klimatyzacji VRF marki Fujitsu oraz montaż windy zewnętrznej.",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-03-psse-pi-a.webp", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-4",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Restauracja Słoneczny Dwór Książ Wlkp.",
    scope: "Montaż klimatyzatora kasetonowego firmy Kaisai",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-04-restauracja-s-oneczny-dwor-ksiaz-wlkp.jpg", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-5",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Komenda Wojewódzka Państwowej Straży Pożarnej w Poznaniu",
    scope: "Montaż systemów VRF oraz agregatow skraplających Daikin, montaż szaf klimatyzacji precyzyjnej",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-05-komenda-wojewodzka-panstwowej-strazy-pozarnej-w-poznaniu.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-6",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Komenda Policji w Luboniu",
    scope: "Montaż Systemów VRF Fujitsu",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-06-komenda-policji-w-luboniu.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-7",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Komenda Policji w Jarocinie",
    scope: "Montaż systemów wody Lodowej oraz wentylacji mechanicznej",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-07-komenda-policji-w-jarocinie.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-8",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "ZUS Środa WLKP",
    scope: "ZUS Środa WLKP - Montaż klimatyzacji",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-08-zus-sroda-wlkp.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-9",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Sąd Rejonowy Piła",
    scope: "Sąd Rejonowy Piła - Montaż systemów klimatyzacji LG\nMontaż systemów Multi Split LG",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-09-sad-rejonowy-pi-a.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-10",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Sąd Rejonowy Kościan",
    scope: "Sąd Rejonowy Kościan - Montaż systemów klimatyzacji LG\nMontaż systemów Split oraz Multi Split LG",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-10-sad-rejonowy-koscian.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-11",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Sala SP3",
    scope: "Sala SP3 - Montaż Systemu Wentylacji Mechanicznej",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-11-sala-sp3.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-12",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Sąd Kamiennogórska",
    scope: "Sąd Kamiennogórska - Systemy VRF LG 0 załącznik",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-12-sad-kamiennogorska.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-13",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Spichlerz Polskiego Rocka",
    scope: "Dostawa oraz montaż systemów C.O. , WOD - KAN , Klimatyzacji opartej na agregatach wody lodowej, wentylacji mechanicznej opartej na centralach wentylacyjnych",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-13-spichlerz-polskiego-rocka.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-14",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Park Wodny Polkowice",
    scope: "Montaż Basenowych Central wentylacyjnych",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-14-park-wodny-polkowice.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-15",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Dworzec PKP Jarocin",
    scope: "Montaż klimatyzatorów typu Split.",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-15-dworzec-pkp-jarocin.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-16",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "PKP CARGO S.A Poznań",
    scope: "-System VRF\n-System Multi Split\n-Split",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-16-pkp-cargo-s-a-poznan.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-17",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Urząd Skarbowy w Jarocinie",
    scope: "Montaż klimatyzatorów typu Split naścienny Sharp",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-17-urzad-skarbowy-w-jarocinie.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-18",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Urząd Gminy Gizałki",
    scope: "Montaż klimatyzatorów typu Split naścienny – Fujitsu",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-18-urzad-gminy-giza-ki.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-19",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "\"Zakład Gospodarki Odpadami\" Sp. z o.o. w Jarocinie",
    scope: "Klimatyzatory Typu Split naścienny Sharp",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-19-zak-ad-gospodarki-odpadami-sp-z-o-o-w-jarocinie.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-20",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Wydział Komunikacji w Jarocinie",
    scope: "Montaż systemów Wody Lodowej , klimatyzacji",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-20-wydzia-komunikacji-w-jarocinie.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-21",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "JANO Sp. z o.o.",
    scope: "Klimatyzatory Typu Split naścienny Fujitsu",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-21-jano-sp-z-o-o.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-22",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Energetyka Poznańska - Przedsiębiorstwo Usług Energetycznych ENERGOBUD Leszno Sp. z o.o Zabytkowy Budynek , Była Ambasada Stanów Zjednoczonych ul. Chopina 1, Poznań",
    scope: "Wymiana całości instalacji centralnego ogrzewania\nSystem Wentylacji Mechanicznej\nSystem Klimatyzacji Centralnej VRF Fujitsu",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-22-energetyka-poznanska-przedsiebiorstwo-us-ug-energetycznych-e.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-23",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Przedsiębiorstwo Wodociągów i Kanalizacji Jarocin",
    scope: "Montaż systemów Split oraz Multi Split Fujitsu",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-23-przedsiebiorstwo-wodociagow-i-kanalizacji-jarocin.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-24",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Miejskie Przedsiębiorstwo Energetyki Cieplnej Sp. z o.o. w Lesznie",
    scope: "System VRF II Fujitsu , System Multi Split Fujitsu",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-24-miejskie-przedsiebiorstwo-energetyki-cieplnej-sp-z-o-o-w-les.png", import.meta.url).href,
  },
  {
    id: "obiekty-uzytecznosci-publicznej-25",
    category: "Obiekty użyteczności publicznej",
    categorySlug: "obiekty-uzytecznosci-publicznej",
    investor: "Nadleśnictwo Jarocin",
    scope: "System VRF II Fujitsu , System Split Fujitsu",
    image: new URL("../assets/realizations/obiekty-uzytecznosci-publicznej-25-nadlesnictwo-jarocin.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-1",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Szpital Szamotuły",
    scope: "Montaż systemów klimatyzacji oraz wentylacji",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-01-szpital-szamotu-y.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-2",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Przychodnia Medyczna Alterida Poznań",
    scope: "Montaż systemów klimatyzacji Split",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-02-przychodnia-medyczna-alterida-poznan.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-3",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Przychodnia Medinet Września",
    scope: "Montaż systemu VRF",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-03-przychodnia-medinet-wrzesnia.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-4",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Hospicjum Poznań",
    scope: "Dostawa oraz montaż systemów klimatyzacji VRF , Split",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-04-hospicjum-poznan.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-5",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Wojewódzki Szpital Dziecięcy im. J. Brudzińskiego w Bydgoszczy",
    scope: "Montaż specjalistycznych klimatyzatorów firmy Daikin z filtrami tytanowo - apatytowo - fotokatalitycznymi.",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-05-wojewodzki-szpital-dzieciecy-im-j-brudzinskiego-w-bydgoszczy.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-6",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Szpital Onkologiczny w Poznaniu",
    scope: "Dostawa oraz montaż systemów klimatyzacji VRF , Split , Multi Split",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-06-szpital-onkologiczny-w-poznaniu.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-7",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Przychodnia “Medicus”",
    scope: "System VRF II Fujitsu , System Split Fujitsu , Wentylacja mechaniczna",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-07-przychodnia-medicus.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-8",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "NZOZ Przychodnia JAR-MEDIC",
    scope: "Montaż Klimatyzatorów typu Split naścienny Sharp / Fujitsu",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-08-nzoz-przychodnia-jar-medic.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-9",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Szpital Opole Specjalistyczny Zespół Neuropsychiatryczny im. Św. Jadwigi",
    scope: "Montaż Klimatyzatorów typu Split / Multi Split naścienny",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-09-szpital-opole-specjalistyczny-zespo-neuropsychiatryczny-im-s.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-10",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Wielospecjalistyczny Szpital Miejski im. Józefa Strusia Poznań",
    scope: "Dostawa oraz montaż systemów klimatyzacji VRF , Split , Multi Split",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-10-wielospecjalistyczny-szpital-miejski-im-jozefa-strusia-pozna.png", import.meta.url).href,
  },
  {
    id: "szpitale-i-placowki-medyczne-11",
    category: "Szpitale i placówki medyczne",
    categorySlug: "szpitale-i-placowki-medyczne",
    investor: "Szpital MSWiA Poznań",
    scope: "Dostawa oraz montaż systemów klimatyzacji VRF , Split , Multi Split, Systemów Wentylacji Mechanicznej",
    image: new URL("../assets/realizations/szpitale-i-placowki-medyczne-11-szpital-mswia-poznan.png", import.meta.url).href,
  },
  {
    id: "banki-1",
    category: "Banki",
    categorySlug: "banki",
    investor: "Bank BGŻ S.A. Pleszew",
    scope: "Klimatyzatory Typu Split naścienny, kasetonowy Fujitsu, wentylacja mechaniczna",
    image: new URL("../assets/realizations/banki-01-bank-bgz-s-a-pleszew.png", import.meta.url).href,
  },
  {
    id: "banki-2",
    category: "Banki",
    categorySlug: "banki",
    investor: "Powiatowy Bank Spółdzielczy w Gostyniu Oddział Borek WLKP",
    scope: "Klimatyzatory Typu Split naścienny Sharp",
    image: new URL("../assets/realizations/banki-02-powiatowy-bank-spo-dzielczy-w-gostyniu-oddzia-borek-wlkp.png", import.meta.url).href,
  },
  {
    id: "banki-3",
    category: "Banki",
    categorySlug: "banki",
    investor: "Powiatowy Bank Spółdzielczy we Wrześni Filia Żerków",
    scope: "Klimatyzatory Typu Split naścienny Sharp / Fujitsu",
    image: new URL("../assets/realizations/banki-03-powiatowy-bank-spo-dzielczy-we-wrzesni-filia-zerkow.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-1",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Dino Polska S.A. Krotoszyn",
    scope: "Montaż systemu wody lodowej, klimatyzacji jeden do jeden, wentylacji, central wentylacyjnych oraz hydrauliki",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-01-dino-polska-s-a-krotoszyn.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-2",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Wielkopolski Zarząd Melioracji i Urządzeń Wodnych",
    scope: "Montaż systemów klimatyzacji Split, Multi Split",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-02-wielkopolski-zarzad-melioracji-i-urzadzen-wodnych.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-3",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "University Business Park GTC S.A.",
    scope: "Montaż Central Wentylacji Mechanicznej",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-03-university-business-park-gtc-s-a.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-4",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "UBIQ BUSINESS PARK",
    scope: "Montaż systemów VRF oraz Split Fujitsu",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-04-ubiq-business-park.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-5",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Andersia Tower Poznań",
    scope: "Dostawa oraz montaż systemów klimatyzacji pomieszczeń technicznych",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-05-andersia-tower-poznan.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-6",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Malta House Poznań",
    scope: "Montaż Systemów Citi Multi oraz Split Mitsubishi",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-06-malta-house-poznan.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-7",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Powiśle Park Sp. z o.o.",
    scope: "Montaż 9 Szaf Klimatyzacji Precyzyjnej Emerson 430kW Mocy chłodniczej",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-07-powisle-park-sp-z-o-o.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-8",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Zabytkowa Kamienica z adaptacją na pomieszczenia biurowe",
    scope: "Montaż klimatyzatorów opartych na systemach Multi oraz wentylacji mechanicznej opartej na centralach wentylacyjnych.",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-08-zabytkowa-kamienica-z-adaptacja-na-pomieszczenia-biurowe.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-9",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Biurowiec BMW MINI Poznań Smorawiński",
    scope: "Montaż systemów VRF",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-09-biurowiec-bmw-mini-poznan-smorawinski.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-10",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Urząd Miasta i Gminy Jastrowie",
    scope: "Montaż systemów VRF",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-10-urzad-miasta-i-gminy-jastrowie.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-11",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Hotel Koźmin",
    scope: "Montaż systemów Citi Multi Mitsubishi",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-11-hotel-kozmin.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-12",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Jarocin Sport Sp. z o.o. w Jarocinie",
    scope: "Montaż Klimatyzatorów typu Split naścienny",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-12-jarocin-sport-sp-z-o-o-w-jarocinie.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-13",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Czardasz - Sala Bankietowo Konferencyjna",
    scope: "Montaż klimatyzatorów typu Split kasetonowy Sharp, wentylacji mechanicznej",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-13-czardasz-sala-bankietowo-konferencyjna.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-14",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Gazeta Jarocińska",
    scope: "Klimatyzatory Typu Split naścienny Sharp",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-14-gazeta-jarocinska.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-15",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "H. Cegielski - Poznań S.A",
    scope: "Montaż klimatyzatorów typu Split naścienny Fujitsu",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-15-h-cegielski-poznan-s-a.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-16",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "VITALIA CONFERENCE CENTRE & RESORT",
    scope: "System VRF System Wody Lodowej oparty na klima-konwektorach typu Split kanałowy, kasetonowy Clint",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-16-vitalia-conference-centre-resort.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-17",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Przemysłowy Instytut Maszyn Rolniczych",
    scope: "Montaż Klimatyzatorów Split oraz Multi Split Fujitsu",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-17-przemys-owy-instytut-maszyn-rolniczych.png", import.meta.url).href,
  },
  {
    id: "obiekty-biurowe-i-hotele-18",
    category: "Obiekty biurowe i hotele",
    categorySlug: "obiekty-biurowe-i-hotele",
    investor: "Poznański Park Technologiczno Przemysłowy",
    scope: "Montaż Klimatyzatorów kanałowych System VRV Daikin",
    image: new URL("../assets/realizations/obiekty-biurowe-i-hotele-18-poznanski-park-technologiczno-przemys-owy.png", import.meta.url).href,
  },
  {
    id: "pozostale-obiekty-1",
    category: "Pozostałe obiekty",
    categorySlug: "pozostale-obiekty",
    investor: "Soho Investments - budynki mieszkalne w Jarocinie, Pleszewie oraz Koźminie Wlkp.",
    scope: "Montaż systemu wentylacji mechanicznej",
    image: new URL("../assets/realizations/pozostale-obiekty-01-soho-investments-budynki-mieszkalne-w-jarocinie-pleszewie-or.jpg", import.meta.url).href,
  },
  {
    id: "pozostale-obiekty-2",
    category: "Pozostałe obiekty",
    categorySlug: "pozostale-obiekty",
    investor: "31 Baza Lotnictwa Taktycznego Krzesiny",
    scope: "Dostosowanie kotłowni olejowych do zmiany paliwa na gaz ziemny oraz budowa instalacji zewnętrznych zasilających kotłownie w gaz ziemny.",
    image: new URL("../assets/realizations/pozostale-obiekty-02-31-baza-lotnictwa-taktycznego-krzesiny.png", import.meta.url).href,
  },
  {
    id: "pozostale-obiekty-3",
    category: "Pozostałe obiekty",
    categorySlug: "pozostale-obiekty",
    investor: "Wielkopolska Okręgowa Izba Inżynierów Budownictwa",
    scope: "Montaż systemu VRF Fujitsu",
    image: new URL("../assets/realizations/pozostale-obiekty-03-wielkopolska-okregowa-izba-inzynierow-budownictwa.jpeg", import.meta.url).href,
  },
  {
    id: "pozostale-obiekty-4",
    category: "Pozostałe obiekty",
    categorySlug: "pozostale-obiekty",
    investor: "Zakład Zagospodarowania Odpadów Jarocin",
    scope: "Montaż systemów: klimatyzacji,wentylacji ,odpylania ,monitorowania powietrza",
    image: new URL("../assets/realizations/pozostale-obiekty-04-zak-ad-zagospodarowania-odpadow-jarocin.png", import.meta.url).href,
  },
  {
    id: "pozostale-obiekty-5",
    category: "Pozostałe obiekty",
    categorySlug: "pozostale-obiekty",
    investor: "Wieża kontroli lotów Krzesiny",
    scope: "System chłodzenia Fujitsu",
    image: new URL("../assets/realizations/pozostale-obiekty-05-wieza-kontroli-lotow-krzesiny.png", import.meta.url).href,
  },
  {
    id: "pozostale-obiekty-6",
    category: "Pozostałe obiekty",
    categorySlug: "pozostale-obiekty",
    investor: "Międzynarodowy Port Lotniczy Katowice w Pyrzowicach",
    scope: "Montaż Systemu chłodzenia wieży kontroli lotów opartego na Wodzie Lodowej",
    image: new URL("../assets/realizations/pozostale-obiekty-06-miedzynarodowy-port-lotniczy-katowice-w-pyrzowicach.png", import.meta.url).href,
  },
  {
    id: "pozostale-obiekty-7",
    category: "Pozostałe obiekty",
    categorySlug: "pozostale-obiekty",
    investor: "Port Lotniczy Poznań-Ławica Sp. z o.o",
    scope: "Montaż 17 klimatyzatorów typu Split naścienny w pomieszczeniach technicznych.",
    image: new URL("../assets/realizations/pozostale-obiekty-07-port-lotniczy-poznan-awica-sp-z-o-o.png", import.meta.url).href,
  },
];
