export const siteConfig = {
  name: "OAT Instalacje",
  tagline: "Projektujemy. Wyceniamy. Realizujemy.",
  founded: 2023,
  realizations: 50,
  phone: "+48 665 610 051",
  phoneDisplay: "665 610 051",
  faxDisplay: "",
  mobilePhone: "+48 665 610 051",
  mobilePhoneDisplay: "665 610 051",
  tax: {
    nip: "",
    regon: "",
  },
  address: {
    street: "",
    postal: "",
    city: "",
    region: "",
    country: "Polska",
  },
  emails: {
    secretariat: "biuro@oatinstalacje.pl",
    secretariatOffice: "biuro@oatinstalacje.pl",
    estimates: "biuro@oatinstalacje.pl",
    service: "biuro@oatinstalacje.pl",
    photovoltaics: "biuro@oatinstalacje.pl",
    serviceManager: "biuro@oatinstalacje.pl",
    accounting: "biuro@oatinstalacje.pl",
    invoices: "biuro@oatinstalacje.pl",
    assembly: "biuro@oatinstalacje.pl",
    estimatesAssistant: "biuro@oatinstalacje.pl",
  },
  contactDepartments: [
    {
      name: "Biuro i zapytania",
      person: "",
      phones: ["665 610 051"],
      fax: "",
      emails: ["biuro@oatinstalacje.pl"],
    },
    {
      name: "Wyceny instalacji",
      person: "",
      phones: ["665 610 051"],
      fax: "",
      emails: ["biuro@oatinstalacje.pl"],
    },
    {
      name: "Realizacje i montaż",
      person: "",
      phones: ["665 610 051"],
      fax: "",
      emails: ["biuro@oatinstalacje.pl"],
    },
    {
      name: "Wsparcie po realizacji",
      person: "",
      phones: ["665 610 051"],
      fax: "",
      emails: ["biuro@oatinstalacje.pl"],
    },
  ],
  contactNotice:
    "Informujemy, iż odpowiedź na Państwa pytanie zostanie udzielona przez firmę OAT Instalacje na podany adres e-mail. Dane z formularza służą wyłącznie do kontaktu w sprawie zapytania, przygotowania wyceny lub obsługi realizacji.",
  partners: [
    "Panasonic", "Hisense", "Kaisai", "AUX", "Immergas", "Klimor", "Viessmann", "KAN"
  ],
  caseStudies: [
    { name: "Domy i mieszkania", city: "Polska", sector: "Klienci indywidualni", scope: "Klimatyzacja, ogrzewanie podłogowe, instalacje wod-kan" },
    { name: "Biura", city: "Polska", sector: "Przestrzenie pracy", scope: "Klimatyzacja, wentylacja i rekuperacja" },
    { name: "Obiekty usługowe", city: "Polska", sector: "Usługi i handel", scope: "Instalacje sanitarne, grzewcze i wentylacyjne" },
    { name: "Inwestorzy", city: "Polska", sector: "Realizacje kompleksowe", scope: "Projekty, wyceny i wykonawstwo instalacji sanitarnych" },
  ],
}
